sudo: required
services:
     - docker

before_install:
     - docker build -t selvendran49/docker-react-demo -f Dockerfile.dev .

script:
     - docker run -e CI=true selvendran49/docker-react-demo npm run test

deploy:
     provider: elasticbeanstalk
     region: "us-east-1"
     app: "docker-react"
     env: "Dockerreact-env-1"
     bucket-name: "elasticbeanstalk-us-east-1-966780937118"
     bucket-path: "docker-react"
     on:
       branch: master
     access_key_id: "$AWS_ACCESS_KEY"
     secret_access_key: "$AWS_SECRET_KEY"