version: '3'
services:
   react-app:
      restart: on-failure
      build: 
        context: .
        dockerfile: Dockerfile.dev
      ports:
       - "80:3000"
      volumes:
         - /app/node_modules
         - .:/app
   tests:
      restart: on-failure
      build: 
        context: .
        dockerfile: Dockerfile
      volumes:
         - /app/node_modules
         - .:/app
      command: ["npm","run","test"]